import { FormattedString } from "@grammyjs/parse-mode";
import { JobStatus } from "../types/ci";
import { createProgressBar } from "./generators";
import { PostMetadata } from "../types/schema";

type StatusMessage = {
    status: JobStatus;
    message: string;
    progress: number | undefined;
}

const statusMap = {
    "completed": {
        icon: "✅",
        title: "Completed!"
    },
    "failed": {
        icon: "❌",
        title: "Failed."
    },
    "pending": {
        icon: "⏳",
        title: "Pending"
    },
    "processing": {
        icon: "⚙️",
        title: "Processing..."
    }
}

export function createStatusMessage({ status, message, progress }: StatusMessage) {
    const statusMessageWithoutProgress = FormattedString.b(`${statusMap[status].icon} Status: `).plain(statusMap[status].title).plain("\n")
        .b("Message: ").plain(message)

    if (status === "completed" || status === "failed" || status === "pending") {
        return statusMessageWithoutProgress;
    }

    return new FormattedString("").concat(statusMessageWithoutProgress).plain("\n\n").plain(`Progress: ${createProgressBar(progress ?? 0)}`)

}

export function createBootanimationPost({ title, creator, details }: Omit<PostMetadata, "download_url" | "video">) {
    return FormattedString.b(`🎞️ ${title}`).plain("\n\n")
        .b("Details:\n")
        .plain("• Resolution: ").code(`${details.resolution.module} [${details.resolution.video}]`).plain("\n")
        .plain("• FPS: ").code(details.fps).plain("\n")
        .plain("• Duration: ").code(`${details.duration}s`).plain("\n")
        .plain("• Type: ").code(details.type)
        .plain("\n\n")
        .b("⚙️ How to Use").plain("\n")
        .plain("Flash the module via your favorite root solution: Magisk / KernelSU")
        .plain("\n\n")
        .b("✨ Credits").plain("\n")
        .plain("• Animation By: ").link(creator.name, `tg://user?id=${creator.user_id}`).plain("\n")
        .plain("• Generated By: @magibootbot")
        .plain("\n\n")
        .plain("👥 Join: @magiboot").plain("\n")
        .plain("📢 Follow for more animations & updates").plain("\n")
        .plain("🛠️ Issues? ").link("Report Here", "https://t.me/magibootchat")
}