import { FormattedString } from "@grammyjs/parse-mode";
import { JobStatus } from "../types/ci";
import { createProgressBar } from "./generators";
import { PostMetadata } from "../types/schema";

type StatusMessage = {
    status: JobStatus;
    message: string;
    progress: number | undefined;
}

export function createStatusMessage({ status, message, progress }: StatusMessage) {
    const statusMap = {
        "completed": "✅ Completed.",
        "failed": "❌ Failed.",
        "pending": "⏳ Pending.",
        "processing": "⚙️ Processing."
    }
    
    if (status === "completed" || status === "failed" || status === "pending") {        
        return FormattedString.b(statusMap[status]).plain(`\n${message}`);
    }

    return FormattedString.b(`${statusMap[status]} `)
    .plain(` ${createProgressBar(progress ?? 0)}\n`)
    .plain(`💬 ${message}`);
}

export function createBootanimationPost({ title, creator, details }: Omit<PostMetadata, "download_url" | "video">) {
    return FormattedString.b(`🎞️ ${title}`).plain("\n\n")
    .b("Details:\n")
    .plain("• Resolution: ").code(`${details.resolution.module} (${details.resolution.video})`).plain("\n")
    .plain("• FPS: ").code(details.fps).plain("\n")
    .plain("• Duration: ").code(`${details.duration}s`).plain("\n")
    .plain("• Type: ").code(details.type)
    .plain("\n\n")
    .b("⚙️ How to Use").plain("\n")
    .plain("Flash the module via your favorite root solution: Magisk / KernelSU")
    .plain("\n\n")
    .b("✨ Credits").plain("\n")
    .plain("• Animation By: ").link(creator.name, `tg://user?id=${creator.user_id}`).plain("\n")
    .plain("• Generated By: @magibootbot")
    .plain("\n\n")
    .plain("👥 Join: @magiboot").plain("\n")
    .plain("📢 Follow for more animations & updates").plain("\n")
    .plain("🛠️ Issues? ").link("Report Here", "https://t.me/magibootchat")
}