name: 'Send Status Update'
description: 'Sends a status update to a webhook. The TELEGRAM_BOT_WEBHOOK_URL environment variable must be set as a secret.'

inputs:
  status:
    description: 'The status to send (pending, processing, completed, failed)'
    required: true
  message:
    description: 'A descriptive message for the status update'
    required: true
  msg_metadata:
    description: 'The Telegram message metadata as a JSON string (must contain chat_id and message_id)'
    required: true
  job_id:
    description: 'An optional job identifier to include in the payload'
    required: false
  data:
    description: 'A JSON string for "completed" status (e.g., post metadata)'
    required: false
  progress:
    description: 'A progress percentage (0-100) for "processing" status'
    required: false
  error_list:
    description: 'A list of errros for "failed" status'
    required: false

runs:
  using: "composite"
  steps:
    - name: "Validate Inputs"
      id: validate
      shell: bash
      # Safely map all action inputs to environment variables
      env:
        INPUT_STATUS: ${{ inputs.status }}
        INPUT_MSG_METADATA: ${{ inputs.msg_metadata }}
        INPUT_DATA: ${{ inputs.data }}
        INPUT_PROGRESS: ${{ inputs.progress }}
        INPUT_ERROR_LIST: ${{ inputs.error_list }}
      run: |
        # Exit immediately if a command exits with a non-zero status.
        set -e

        echo "TELEGRAM_BOT_WEBHOOK_URL: $TELEGRAM_BOT_WEBHOOK_URL"

        # --- Basic Validations ---
        if [[ -z "$INPUT_MSG_METADATA" ]]; then
          echo "❌ Error: msg_metadata is required." >&2
          exit 1
        fi

        # Validate JSON by echoing the environment variable
        if ! echo "$INPUT_MSG_METADATA" | jq -e . >/dev/null; then
          echo "❌ Error: msg_metadata must be a valid JSON object." >&2
          exit 1
        fi
        
        # --- Extract and Validate Metadata ---
        CHAT_ID=$(echo "$INPUT_MSG_METADATA" | jq -r '.chat_id')
        MESSAGE_ID=$(echo "$INPUT_MSG_METADATA" | jq -r '.message_id')

        if [[ -z "$CHAT_ID" || "$CHAT_ID" == "null" || -z "$MESSAGE_ID" || "$MESSAGE_ID" == "null" ]]; then
          echo "❌ Error: msg_metadata must contain non-null 'chat_id' and 'message_id' keys." >&2
          exit 1
        fi
        
        # --- Conditional Validations based on status ---
        case "$INPUT_STATUS" in
          processing)
            if [[ -z "$INPUT_PROGRESS" ]]; then
              echo "❌ Error: 'progress' input is required for 'processing' status." >&2
              exit 1
            fi
            ;;
          completed)
            if [[ -z "$INPUT_DATA" ]]; then
              echo "❌ Error: 'data' input is required for 'completed' status." >&2
              exit 1
            fi
            ;;
          failed)
            if [[ -z "$INPUT_ERROR_LIST"]]; then
              echo "❌ Error: 'error_list' input is required for 'failed' status." >&2
              exit 1
            
            # This is the corrected line, now reading from a safe environment variable
            if ! echo "$INPUT_DATA" | jq -e . >/dev/null; then
              echo "❌ Error: 'data' input must be a valid JSON string for 'completed' status." >&2
              exit 1
            fi
            ;;
        esac

        # --- Expose validated data to subsequent steps ---
        echo "chat_id=$CHAT_ID" >> "$GITHUB_OUTPUT"
        echo "message_id=$MESSAGE_ID" >> "$GITHUB_OUTPUT"

    - name: "Generate JSON Payload"
      id: generate_payload
      shell: bash
      env:
        # Map all necessary inputs and prior step outputs to env vars
        INPUT_STATUS: ${{ inputs.status }}
        INPUT_MESSAGE: ${{ inputs.message }}
        INPUT_CHAT_ID: ${{ steps.validate.outputs.chat_id }}
        INPUT_MESSAGE_ID: ${{ steps.validate.outputs.message_id }}
        INPUT_JOB_ID: ${{ inputs.job_id }}
        INPUT_PROGRESS: ${{ inputs.progress }}
        INPUT_DATA: ${{ inputs.data }}
        INPUT_ERROR_LIST: ${{ inputs.error_list }}
      run: |
        set -e

        # Build the base JSON payload using the safe env vars
        BASE_PAYLOAD=$(jq -n \
          --arg status "$INPUT_STATUS" \
          --arg message "$INPUT_MESSAGE" \
          --argjson chatId "$INPUT_CHAT_ID" \
          --argjson messageId "$INPUT_MESSAGE_ID" \
          '{
            status: $status,
            message: $message,
            tg_metadata: {
              "chatId": $chatId,
              "messageId": $messageId
            }
          }')

        # Conditionally add fields to the payload
        case "$INPUT_STATUS" in
          processing)
            PAYLOAD=$(echo "$BASE_PAYLOAD" | jq --argjson progress "$INPUT_PROGRESS" '. + {progress: $progress}')
            ;;
          completed)
            # Safely parse the data using --argjson instead of --arg and fromjson
            PAYLOAD=$(echo "$BASE_PAYLOAD" | jq --argjson data "$INPUT_DATA" '. + {post_metadata: $data}')
            if [[ -n "$INPUT_JOB_ID" ]]; then
              PAYLOAD=$(echo "$PAYLOAD" | jq --arg jobId "$INPUT_JOB_ID" '. + {job_id: $jobId}')
            fi
            ;;
          failed)
            PAYLOAD=$(echo "$BASE_PAYLOAD" | jq --argjson error_list "$ERROR_LIST" '. + {error_list: $error_list}')
            if [[ -n "$INPUT_JOB_ID" ]]; then
              PAYLOAD=$(echo "$PAYLOAD" | jq --arg jobId "$INPUT_JOB_ID" '. + {job_id: $jobId}')
            fi
            ;;
          pending)
            PAYLOAD="$BASE_PAYLOAD"
            if [[ -n "$INPUT_JOB_ID" ]]; then
              PAYLOAD=$(echo "$PAYLOAD" | jq --arg jobId "$INPUT_JOB_ID" '. + {job_id: $jobId}')
            fi
            ;;
          *)
            echo "❌ Error: Invalid status '$INPUT_STATUS' encountered." >&2
            exit 1
            ;;
        esac

        echo "payload=$(echo "$PAYLOAD" | jq -c '.')" >> "$GITHUB_OUTPUT"

    - name: "Send Payload to Webhook"
      id: send_payload
      shell: bash
      run: |
        set -e
        
        # Check that the webhook URL secret is available
        : "${TELEGRAM_BOT_WEBHOOK_URL?Error: TELEGRAM_BOT_WEBHOOK_URL environment variable must be set.}"

        echo "🚀 Sending notification..."
        curl --request POST \
             --header "Content-Type: application/json" \
             --data '${{ steps.generate_payload.outputs.payload }}' \
             --silent --show-error --fail \
             "$TELEGRAM_BOT_WEBHOOK_URL"
        
        echo "✅ Notification sent successfully."